### ISSUE TITLE
Can`t connect to server from GUI.

### ISSUE THREAD

**Issue by BytEvil** [RuiSiang/PoW-Phalanx#5]
Hi. Can`t connect to server from GUI.
PHALANX ENDPOINT:
http://192.168.100.103:6000?token=test-controller-token
PoW Shield connected and subscribed to controller channel, but PoW Phalanx Controller Dashboard says Please wait..., No data recieved for..., Not connected to socket!

**Comment by RuiSiang** [comment]
I just tested with the newest code, it all works. Probably your issue is that your hostname/port is wrong or that PoW-Phalanx is not set up properly.

**Comment by BytEvil** [comment]
Hi. PoW-Phalanx compiled by default with .env, containing:
```
PORT=6000
DATABASE_HOST=127.0.0.1
DATABASE_PORT=6379
DATABASE_PASSWORD=
SUBSCRIPTION_TOKEN=test-subscription-token
CONTROLLER_TOKEN=dDyvwMMWA94veS8WvMGJlO3tK5cwuw2b
MODEL_TOKEN=test-model-token
CONTROLLER_BROADCAST_INTERVAL=20
STAT_FETCH_INTERVAL=10
STAT_KEEP_HISTORY_TIME=3600
RESOURCE_MONITOR=off
RESOURCE_MONITOR_HOST=
RESOURCE_MONITOR_PORT=
SETTINGS_FETCH=off
```
and controller worked and listen on port 6000:
`tcp6       0      0 :::6000                 :::*                    LISTEN      1941/node`

pow-shield compiled with .env, containing:
```
SOCKET=on
SOCKET_URL=http://192.168.100.103:6000
SOCKET_TOKEN=dDyvwMMWA94veS8WvMGJlO3tK5cwuw2b
```
and succesfully connected to Phalanx controller:
`npm[1941]: Client QhC51UX0xq9PAOJrAAAB connected and subscribed to controller channel`

POW-Phalanx GUI started:
```
- Local:            http://localhost:3000
- On Your Network:  http://192.168.100.103:3000
```
POW PHALANX ENDPOINT:
`http://192.168.100.103:6000?token=dDyvwMMWA94veS8WvMGJlO3tK5cwuw2b`

What's wrong? :)

**Comment by RuiSiang** [comment]
pow-shield and GUI are both on port 3000...

**Comment by BytEvil** [comment]
pow shield on port 1934:
`tcp6       0      0 :::1934                 :::*                    LISTEN      1913/node`
.env
```
PORT=1934
SESSION_KEY="abcdefghijklmnop"
POW=on
NONCE_VALIDITY=60000
DIFFICULTY=13
BACKEND_URL="http://192.168.100.103"

DATABASE_HOST=127.0.0.1
DATABASE_PORT=6379
DATABASE_PASSWORD=

RATE_LIMIT=on
RATE_LIMIT_SAMPLE_MINUTES=60
RATE_LIMIT_SESSION_THRESHOLD=100
RATE_LIMIT_BAN_IP=on
RATE_LIMIT_IP_THRESHOLD=500
RATE_LIMIT_BAN_MINUTES=15

WAF=on
WAF_URL_EXCLUDE_RULES=
WAF_HEADER_EXCLUDE_RULES=14,33,80,96,100,45
WAF_BODY_EXCLUDE_RULES=

SSL=off
SSL_CERT_PATH=
SSL_KEY_PATH=
SOCKET=on
SOCKET_URL=http://192.168.100.103:6000
SOCKET_TOKEN=dDyvwMMWA94veS8WvMGJlO3tK5cwuw2b
```
